# Generated by Django 5.0.2 on 2024-03-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
