# Generated by Django 5.0.2 on 2024-03-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedPosts',
        ),
    ]
