# Generated by Django 5.0.2 on 2024-03-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0024_alter_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.post'),
        ),
    ]
